// src/components/vue/theme-menu.vue
<script setup lang="ts">
  import { effect } from "vue";
  import { useStore } from "@nanostores/vue";
  import { Sun, Moon } from "lucide-vue-next";


  import { Button } from "~/components/vue/ui/button";
  import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "~/components/vue/ui/dropdown-menu";

  import { theme, useTheme, setTheme, toggleTheme } from "~/stores/theme-store"

  const $theme = useStore(theme)

  effect(() => {
    useTheme($theme.value)
  })

</script>

<template>
  <DropdownMenu>
    <DropdownMenuTrigger asChild>
      <Button variant="outline" size="icon">
        <Sun class="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
        <Moon class="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
        <span class="sr-only">Toggle theme</span>
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent align="end">
      <DropdownMenuItem @click="() => setTheme('light')">Light</DropdownMenuItem>
      <DropdownMenuItem @click="() => setTheme('dark')">Dark</DropdownMenuItem>
      <DropdownMenuItem @click="() => setTheme('system')">System</DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

// src/components/react/theme/theme-menu.react.tsx
import { useEffect } from "react";
import { Sun, Moon } from "lucide-react";
import { useStore } from "@nanostores/react";
import { theme, useTheme, setTheme } from "~/stores/theme-store";
import { Button } from "~/components/react/ui/button";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "~/components/react/ui/dropdown-menu";

export default function ThemeToggle() {
  const $theme = useStore(theme);

  useEffect(() => {
    useTheme($theme);
  }, [$theme]);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="icon">
          <Sun className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
          <Moon className="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
          <span className="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => setTheme("light")}>
          Light
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("dark")}>
          Dark
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("system")}>
          System
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
