// src/components/vue/theme/theme-toggle.vue
<script setup lang="ts">
  import { Sun, Moon } from "lucide-vue-next";
  import { toggleTheme } from "~/stores/theme-store";
  import { Button } from "~/components/vue/ui/button";
</script>

<template>
  <Button @click="toggleTheme" variant="outline" size="icon">
    <Sun class="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
    <Moon class="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
    <span class="sr-only">Toggle theme</span>
  </Button>
</template>

// src/components/react/theme/theme-toggle.react.tsx
import { Sun, Moon } from "lucide-react";
import { toggleTheme } from "~/stores/theme-store";
import { Button } from "~/components/react/ui/button";

export default function ThemeToggle() {
  return (
    <Button onClick={toggleTheme} variant="outline" size="icon">
      <Sun className="h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
      <Moon className="absolute h-[1.2rem] w-[1.2rem] dark:-rotate-90 scale-100 transition-all rotate-0 dark:scale-0" />
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}
