// src/components/svelte/ui/button/button.svelte
<script lang="ts">
	import { Button as ButtonPrimitive } from "bits-ui";
	import { cn } from "~/lib/utils.js";
	import { buttonVariants, type Props, type Events } from "./index.js";

	type $$Props = Props;
	type $$Events = Events;

	let className: $$Props["class"] = undefined;
	export let variant: $$Props["variant"] = "default";
	export let size: $$Props["size"] = "default";
	export let builders: $$Props["builders"] = [];
	export { className as class };
</script>

<ButtonPrimitive.Root
	{builders}
	class={cn(buttonVariants({ variant, size, className }))}
	type="button"
	{...$$restProps}
	on:click
	on:keydown
>
	<slot />
</ButtonPrimitive.Root>

// src/components/vue/ui/button/Button.vue
<script setup lang="ts">
  import type { HTMLAttributes } from "vue";
  import { Primitive, type PrimitiveProps } from "radix-vue";
  import { type ButtonVariants, buttonVariants } from ".";
  import { cn } from "~/lib/utils";

  interface Props extends PrimitiveProps {
    variant?: ButtonVariants["variant"];
    size?: ButtonVariants["size"];
    class?: HTMLAttributes["class"];
  }

  const props = withDefaults(defineProps<Props>(), {
    as: "button",
  });
</script>

<template>
  <Primitive
    :as="as"
    :as-child="asChild"
    :class="cn(buttonVariants({ variant, size }), props.class)"
  >
    <slot />
  </Primitive>
</template>
